### ISSUE TITLE
minLength option

### ISSUE THREAD

**Issue by FND** [innoq/simplete.obsolete#4]
cf. http://api.jqueryui.com/autocomplete/#option-minLength

**Comment by FND** [comment]
I'm not convinced such an option is actually sensible: We're already ensuring that the server isn't being hammered by debouncing requests - beyond that, it's the server's job to decide whether a query can be fulfilled or not and to respond accordingly (for a somewhat absurd example, imagine that single letters are insufficient to produce results while single emoji are perfectly sensible - we wouldn't want the client to make that distinction).

Opinions, @rstrangh @mrreynolds @christophw @mrsellars @cdent?

**Comment by cdent** [comment]
What if someone wants to use simplete in a situation where they have no control over or relationship with the server?

You say "we wouldn't want the client to make that distinction" but what if the server side is pathological but still a useful resource. In that setting "we wouldn't want the server making all the decisions".

**Comment by FND** [comment]
done with 1c0ce0d5136cf17b5809b554850a2dd3124e2f6e
